# Generated by Django 4.0.4 on 2022-05-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='River',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('itinerary', models.TextField(max_length=1000)),
                ('duration', models.CharField(max_length=100)),
                ('difficulty', models.IntegerField()),
            ],
            options={
                'ordering': ['difficulty'],
            },
        ),
    ]
